version: '3'

networks: 
  kafka-network:

services: 
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      # - ./mysql:/var/lib/mysql
      - ./data/:/docker-entrypoint-initdb.d
    restart: 'always'
    environment:
      MYSQL_DATABASE: 'coupon_system'
      MYSQL_ROOT_PASSWORD: 'rootpass'
      MYSQL_USER: 'couponadmin'
      MYSQL_PASSWORD: 'couponpass'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - '3307:3306'

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports: 
      - '2181:2181'
    networks: 
      - kafka-network
  
  kafka:
    image: wurstmeister/kafka:2.12-2.0.1
    container_name: kafka
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    environment: 
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: 'notification:7:1' # Topic명:Partition개수:Replica개수
    ports: 
      - '9092:9092'
    depends_on: 
      - zookeeper
    networks: 
      - kafka-network