spring:
    h2:
        console:
            enabled: true

    datasource:
        platform: h2
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:coupon_system
        username: sa
        sql-script-encoding: UTF-8

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        show-sql: true